import Link from 'next/link'
import Head from 'next/head'
import Image from 'next/image'
import { UilLinkedin } from '@iconscout/react-unicons'
import { UilGithub } from '@iconscout/react-unicons'
import { UilMessage } from '@iconscout/react-unicons'
import { UilMouseAlt } from '@iconscout/react-unicons'
import { UilArrowDown } from '@iconscout/react-unicons'
import { UilDownloadAlt } from '@iconscout/react-unicons'
import portrait from '../assets/portrait.png'

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<div className='body'>
				<main className='main'>
					{/* ==================== HOME ==================== */}
					<section className='home section' id='home'>
						<div className='home__container container grid'>
							<div className='home__content grid'>
								<div className='home__social'>
									<Link
										href='https://www.linkedin.com/in/julie-poirson273/'
										target='_blank'
										className='home__social-icon'
									>
										<p>
											<UilLinkedin />
										</p>
									</Link>
									<Link
										href='https://github.com/jujujup'
										target='_blank'
										className='home__social-icon'
									>
										<p>
											<UilGithub />
										</p>
									</Link>
								</div>
								<div className='home__img'>
									<Image src={portrait} />
								</div>

								<div className='home__data'>
									<h1 className='home__title'>Hi, I am Julie</h1>
									<h3 className='home__subtitle'>
										Engineering & marketing student
									</h3>
									<p className='home__description'>
										Results driven and inquisitive engineering student currently
										pursuing a double major in information systems,
										cybersecurity, data science & marketing.
									</p>
									<Link href='/contact' className='button button--flex'>
										Contact Me
										<p className='button__icon'>
											<UilMessage />
										</p>
									</Link>
								</div>
							</div>
							<div className='home__scroll'>
								<Link
									href='/about'
									className='home__scroll-button button--flex'
								>
									<p className='home__scroll-mouse'>
										<UilMouseAlt />
									</p>
									<span className='home__scroll-name'> Scroll down </span>
									<p className='home__scroll-arrow'>
										<UilArrowDown />
									</p>
								</Link>
							</div>
						</div>
					</section>

					{/* ==================== ABOUT ==================== */}
					<section className='about section' id='about'>
						<h2 className='section__title'>About Me</h2>
						<span className='section__subtitle'>My introduction</span>

						<div className='about__container container grid'>
							<Image alt='' className='about__img' />

							<div className='about__data'>
								<p className='about__description'>Highly motivated,</p>

								{/* <div className='about__info'>
									<div>
										<span className='about__info-title'>0</span>
										<span className='about__info-name'>
											Years <br />
											experience
										</span>
									</div>
									<div>
										<span className='about__info-title'>0</span>
										<span className='about__info-name'>
											Completed <br />
											projects
										</span>
									</div>
									<div>
										<span className='about__info-title'>0</span>
										<span className='about__info-name'>
											Companies <br />
										</span>
									</div>
								</div> */}
								<div className='about__buttons'>
									<a
										download=''
										href='../assets/resume-julie-poirson.pdf'
										className='button button--flex'
									>
										Download resume
										<p className='button__icon'>
											<UilDownloadAlt />
										</p>
									</a>
								</div>
							</div>
						</div>
					</section>
					{/* ==================== SKILLS ==================== */}
					<section className='skills section' id='skills'>
						<h2 className='section__title'>Skills</h2>
						<span className='section__subtitle'>My technical level</span>
						<div className='skills__container container grid'>
							{/* ==================== SKILLS 1 ==================== */}
							<div className='skills__content skills__open'>
								<div className='skills__header'>
									<i className='uil uil-crosshair skills__icon'></i>

									<div>
										<h1 className='skills__title'>Marketing</h1>
										<span className='skills__subtitle'>2 years</span>
									</div>

									<i className='uil uil-angle-down skills__arrow'></i>
								</div>

								<div className='skills__list grid'>
									<div className='skills__data'>
										<div className='skills__titles'>
											<h3 className='skills__name'>Inbound Marketing</h3>
											<span className='skills__number'>80%</span>
										</div>
										<div className='skills__bar'>
											<span className='skills__percentage skills__inbound'></span>
										</div>
									</div>
									<div className='skills__data'>
										<div className='skills__titles'>
											<h3 className='skills__name'>Marketing Research</h3>
											<span className='skills__number'>50%</span>
										</div>
										<div className='skills__bar'>
											<span className='skills__percentage skills__research'></span>
										</div>
									</div>
									<div className='skills__data'>
										<div className='skills__titles'>
											<h3 className='skills__name'>Hubspot</h3>
											<span className='skills__number'>40%</span>
										</div>
										<div className='skills__bar'>
											<span className='skills__percentage skills__hubspot'></span>
										</div>
									</div>
								</div>
							</div>

							{/* ==================== SKILLS 2 ==================== */}
							<div className='skills__content skills__close'>
								<div className='skills__header'>
									<i className='uil uil-swatchbook skills__icon'></i>
									<div>
										<h1 className='skills__title'>Graphic Design</h1>
										<span className='skills__subtitle'> ~About two years</span>
									</div>

									<i className='uil uil-angle-down skills__arrow'></i>
								</div>

								<div className='skills__list grid'>
									<div className='skills__data'>
										<div className='skills__titles'>
											<h3 className='skills__name'>Canva</h3>
											<span className='skills__number'>80%</span>
										</div>
										<div className='skills__bar'>
											<span className='skills__percentage skills__canva'></span>
										</div>
									</div>
									<div className='skills__data'>
										<div className='skills__titles'>
											<h3 className='skills__name'>Photoshop</h3>
											<span className='skills__number'>10%</span>
										</div>
										<div className='skills__bar'>
											<span className='skills__percentage skills__photoshop'></span>
										</div>
									</div>
								</div>
							</div>

							{/* ==================== SKILLS 3 ==================== */}
							<div className='skills__content skills__close'>
								<div className='skills__header'>
									<i className='uil uil-brackets-curly skills__icon'></i>

									<div>
										<h1 className='skills__title'>Programming</h1>
										<span className='skills__subtitle'>Less than a year</span>
									</div>

									<i className='uil uil-angle-down skills__arrow'></i>
								</div>

								<div className='skills__list grid'>
									<div className='skills__data'>
										<div className='skills__titles'>
											<h3 className='skills__name'>SQL</h3>
											<span className='skills__number'>50%</span>
										</div>
										<div className='skills__bar'>
											<span className='skills__percentage skills__sql'></span>
										</div>
									</div>
									<div className='skills__data'>
										<div className='skills__titles'>
											<h3 className='skills__name'>Java</h3>
											<span className='skills__number'>30%</span>
										</div>
										<div className='skills__bar'>
											<span className='skills__percentage skills__java'></span>
										</div>
									</div>
									<div className='skills__data'>
										<div className='skills__titles'>
											<h3 className='skills__name'>HTML</h3>
											<span className='skills__number'>30%</span>
										</div>
										<div className='skills__bar'>
											<span className='skills__percentage skills__html'></span>
										</div>
									</div>
									<div className='skills__data'>
										<div className='skills__titles'>
											<h3 className='skills__name'>Python</h3>
											<span className='skills__number'>20%</span>
										</div>
										<div className='skills__bar'>
											<span className='skills__percentage skills__python'></span>
										</div>
									</div>
								</div>
							</div>
						</div>
					</section>
					{/* ==================== QUALIFICATION ==================== */}
					<section class='qualification section'>
						<h2 class='section__title'>Qualification</h2>
						<span class='section__subtitle'>My personal journey</span>

						<div class='qualification__container container'>
							<div class='qualification__tabs'>
								<div
									class='qualification__button button--flex qualification__active'
									data-target='#education'
								>
									<i class='uil uil-graduation-cap qualification__icon'></i>
									Education
								</div>

								<div
									class='qualification__button button--flex'
									data-target='#work'
								>
									<i class='uil uil-briefcase-alt qualification__icon'></i>
									Work
								</div>
							</div>
							<div class='qualification__sections'>
								{/* ==================== QUALIFICATION CONTENT 1 ==================== */}
								<div
									class='qualification__content qualification__active'
									data-content
									id='education'
								>
									{/* ==================== QUALIFICATION 1 ==================== */}
									<div class='qualification__data'>
										<div>
											<h3 class='qualification__title'>Law School</h3>
											<span class='qualification__subtitle'>
												Nanterre University
											</span>
											<div class='qualification__calendar'>
												<i class='uil uil-calendar-alt'></i>
												2018 - 2020
											</div>
										</div>
										<div>
											<span class='qualification__rounder'></span>
											<span class='qualification__line'></span>
										</div>
									</div>

									{/* ==================== QUALIFICATION 2 ==================== */}
									<div class='qualification__data'>
										<div></div>

										<div>
											<span class='qualification__rounder'></span>
											<span class='qualification__line'></span>
										</div>

										<div>
											<h3 class='qualification__title'>Master in Marketing</h3>
											<span class='qualification__subtitle'>ESCE Paris</span>
											<div class='qualification__calendar'>
												<i class='uil uil-calendar-alt'></i>
												2020 - 2023
											</div>
										</div>
									</div>
									{/* ==================== QUALIFICATION 3 ==================== */}
									<div class='qualification__data'>
										<div>
											<h3 class='qualification__title'>
												Exchange semester in Kansas (US)
											</h3>
											<span class='qualification__subtitle'>
												Wichita State University
											</span>
											<div class='qualification__calendar'>
												<i class='uil uil-calendar-alt'></i>
												2022
											</div>
										</div>
										<div>
											<span class='qualification__rounder'></span>
											<span class='qualification__line'></span>
										</div>
									</div>
									{/* ==================== QUALIFICATION 4 ==================== */}
									<div class='qualification__data'>
										<div></div>

										<div>
											<span class='qualification__rounder'></span>
											{/* <!--span class="qualification__line"></span> --> */}
										</div>

										<div>
											<h3 class='qualification__title'>
												Master in Information Systems, Big data & Analytics
											</h3>
											<span class='qualification__subtitle'>ECE Paris</span>
											<div class='qualification__calendar'>
												<i class='uil uil-calendar-alt'></i>
												2022 - 2024
											</div>
										</div>
									</div>
								</div>
								{/* ==================== QUALIFICATION CONTENT 2 ==================== */}
								<div class='qualification__content' data-content id='work'>
									{/* ==================== QUALIFICATION 1 ==================== */}
									<div class='qualification__data'>
										<div>
											<h3 class='qualification__title'>Marketing Assistant</h3>
											<span class='qualification__subtitle'>Eventtia</span>
											<div class='qualification__calendar'>
												<i class='uil uil-calendar-alt'></i>3 months - 2021
											</div>
										</div>
										<div>
											<span class='qualification__rounder'></span>
											<span class='qualification__line'></span>
										</div>
									</div>
									{/* <!--==================== QUALIFICATION 2 ====================
							<div class="qualification__data">
								<div></div>

								<div>
									<span class="qualification__rounder"></span>
									<span class="qualification__line"></span>
								</div>

								<div>
									<h3 class="qualification__title">...</h3>
									<span class="qualification__subtitle"></span>
									<div class="qualification__calendar">
										<i class="uil uil-calendar-alt"></i>
									</div>
								</div>
							</div> --> */}
								</div>
							</div>
						</div>
					</section>
					{/* ==================== PORTFOLIO ==================== */}
					<section class='portfolio section' id='portfolio'>
						<h2 class='section__title'>Portfolio</h2>
						<span class='section__subtitle'>Most recent work</span>

						<div class='portfolio__container container swiper-container'>
							<div class='swiper-wrapper'>
								{/* ==================== PORTFOLIO 1 ==================== */}
								<div class='portfolio__content grid swiper-slide'>
									<img
										src='assets/img/portfolio1.jpg'
										alt=''
										class='portfolio__img'
									/>

									<div class='portfolio__data'>
										<h3 class='portfolio__title'>Modern Website</h3>
										<p class='portfolio__description'>description</p>
										<a
											href='#'
											class='button button--flex button--small portfolio__button'
										>
											Demo
											<i class='uil uil-arrow-right button__icon'></i>
										</a>
									</div>
								</div>
								{/* ==================== PORTFOLIO 2 ==================== */}
								<div class='portfolio__content grid swiper-slide'>
									<img
										src='assets/img/portfolio2.jpg'
										alt=''
										class='portfolio__img'
									/>

									<div class='portfolio__data'>
										<h3 class='portfolio__title'>Brand design</h3>
										<p class='portfolio__description'>description</p>
										<a
											href='#'
											class='button button--flex button--small portfolio__button'
										>
											Demo
											<i class='uil uil-arrow-right button__icon'></i>
										</a>
									</div>
								</div>
								{/* ==================== PORTFOLIO 3 ==================== */}
								<div class='portfolio__content grid swiper-slide'>
									<img
										src='assets/img/portfolio3.jpg'
										alt=''
										class='portfolio__img'
									/>

									<div class='portfolio__data'>
										<h3 class='portfolio__title'>Online Store</h3>
										<p class='portfolio__description'>description</p>
										<a
											href='#'
											class='button button--flex button--small portfolio__button'
										>
											Demo
											<i class='uil uil-arrow-right button__icon'></i>
										</a>
									</div>
								</div>
							</div>
							{/* <!-- Add arrows--> */}
							<div class='swiper-button-next'>
								<i class='uil uil-angle-right-b swiper-portfolio-icon'></i>
							</div>
							<div class='swiper-button-prev'>
								<i class='uil uil-angle-left-b swiper-portfolio-icon'></i>
							</div>

							{/* <!-- Add pagination--> */}
							<div class='swiper-pagination'></div>
						</div>
					</section>

					{/* ==================== PROJECT IN MIND ==================== */}
					<section class='project section'>
						<div class='project__bg'>
							<div class='project__container container grid'>
								<div class='project__data'>
									<h2 class='project__title'>Looking for an intern?</h2>
									<p class='project__description'>
										Don't hesitate to reach out!
									</p>
									<a href='#' class='button button--flex button--white'>
										Contact Me
										<i class='uil uil-message project__icon button__icon'></i>
									</a>
								</div>
							</div>
						</div>
					</section>

					{/* ==================== CONTACT ME ==================== */}
					<section class='contact section' id='contact'>
						<h2 class='section__title'>Contact me</h2>
						<span class='section__subtitle'>Let's get in touch!</span>

						<div class='contact__container container grid'>
							<div>
								<div class='contact__information'>
									<i class='uil uil-phone contact__icon'></i>

									<div>
										<h3 class='contact__title'>Call me</h3>
										<span class='contact__subtitle'>+33 6 95 27 16 80</span>
									</div>
								</div>
								<div class='contact__information'>
									<i class='uil uil-envelope contact__icon'></i>

									<div>
										<h3 class='contact__title'>Email</h3>
										<span class='contact__subtitle'>julie.lp273@gmail.com</span>
									</div>
								</div>
								<div class='contact__information'>
									<i class='uil uil-map-marker contact__icon'></i>
									<div>
										<h3 class='contact__title'>Location</h3>
										<span class='contact__subtitle'>Paris - France</span>
									</div>
								</div>
							</div>
							<form action='' class='contact__form grid'>
								<div class='contact__inputs grid'>
									<div class='contact__content'>
										<label for='' class='contact__label'>
											Name
										</label>
										<input type='text' class='contact__input' />
									</div>
									<div class='contact__content'>
										<label for='' class='contact__label'>
											Email
										</label>
										<input type='email' class='contact__input' />
									</div>
								</div>
								<div class='contact__content'>
									<label for='' class='contact__label'>
										Message
									</label>
									<textarea
										name=''
										id=''
										cols='0'
										rows='7'
										class='contact__input'
									></textarea>
								</div>

								<div>
									<a href='' class='button button--flex'>
										Send Message
										<i class='uil uil-message button__icon'></i>
									</a>
								</div>
							</form>
						</div>
					</section>
				</main>
			</div>
		</>
	)
}
