import Head from 'next/head'
import Image from 'next/image'

import knc from '../assets/knc.png'

import { UilCrosshair } from '@iconscout/react-unicons'
import { UilQuestionCircle } from '@iconscout/react-unicons'
import { UilNotes } from '@iconscout/react-unicons'

export default function Home() {
	return (
		<>
			<Head>
				<title>Julie Poirson's portfolio - KNC project</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<div className='body'>
				<main className='main'>
					<section className='portfolioproject__section'>
						<h1 className='section__title'>KNC project</h1>
						<span className='section__subtitle'>
							Marketing research project
						</span>
						<div className='portfolioproject__container container grid'>
							<Image src={knc} className='portfolioproject__img' />
							<div className='portfolioproject__home'>
								<p className='portfolioproject__text'>
									In the spring semester of 2022, I had the opportunity to
									conduct a study for an organization my Marketing Research
									class at WSU partnered with: the{' '}
									<strong>Kansas Nonprofit Chamber</strong> (KNC).
									<br />
								</p>
								<p className='portfolioproject__text'>
									The KNC wanted to know ways they could improve their service
									to{' '}
									<strong>
										increase their membership rate in order to grow and expand
										the organization
									</strong>
									.
									<br />
								</p>
								<p className='portfolioproject__text'>
									To provide them with an answer, we helped administer a survey
									to gather data for reasons why nonprofits are not currently
									paying members of the KNC.
								</p>
							</div>
						</div>
						<div className='portfolioproject__container container'>
							<h2 className='section__title2'>
								<UilCrosshair className='portfolioproject__icon' />
								Our goals were to:
							</h2>
							<p className='portfolioproject__text'>
								- Provide insight into how nonprofits are faring in this
								economy,
							</p>
							<p className='portfolioproject__text'>
								- Narrow down the expenses nonprofits spend the most on,
							</p>
							<p className='portfolioproject__text'>
								- Help determine if the membership costs of the Kansas Nonprofit
								Chamber are beneficial.
							</p>
						</div>
						<div className='portfolioproject__container container paragraph__right'>
							<h2 className='section__title2'>
								We formulated two hypotheses:
								<UilQuestionCircle className='portfolioproject__icon' />
							</h2>
							<p className='portfolioproject__text'>
								<strong>1.</strong> Non-members rate the importance of the cost
								of membership at least a 4 on a 5 point-scale.
							</p>
							<p className='portfolioproject__text'>
								<strong>2.</strong> To non-members, the cost of the membership
								fee is a more important reason <br /> for not joining the KNC
								than any other reason/applicability.
							</p>
						</div>
						<div className='portfolioproject__container container'>
							<h2 className='section__title2'>
								<UilNotes className='portfolioproject__icon' />
								Survey methods
							</h2>
							<p className='portfolioproject__text'>
								A <strong>survey</strong> was created by collaboration between
								MKT 403 students in spring 2022 and was sent via email.
							</p>
							<p className='portfolioproject__text'>
								<strong>Target population:</strong> All nonprofit members
								subscribed to the Kansas Nonprofit Chamber email list
							</p>
							<p className='portfolioproject__text'>
								<strong>Sampling Frame:</strong> Kansas Nonprofit Chamber email
								list (N=2,600)
							</p>
							<p className='portfolioproject__text'>
								Minimize coverage, measurement, and nonresponse error by:
								<br />
								- Approximating 10 minutes to complete
								<br />
								- Noting survey was anonymous
								<br />
								- Describing program offerings
								<br />
								- Display logic to avoid inaccurate answers
								<br />
								- Dividing length of operation status into intervals
								<br />- Reviewing questions by students, professor, and client
							</p>
						</div>
						<div className='portfolioproject__container container'>
							<h2 className='section__title2'>
								<UilNotes className='portfolioproject__icon' />
								About the Kansas Nonprofit Chamber (KNC)
							</h2>
							<p className='portfolioproject__text'>
								The <strong>Kansas Nonprofit Chamber (KNC)</strong> is an
								organization focusing on supporting nonprofits across Kansas.
							</p>
							<p className='portfolioproject__text'>
								The KNC offers a number of programs and services dedicated to
								helping nonprofits statewide to grow and reach their individual
								goals.
							</p>
							<p className='portfolioproject__text'>
								With the large amount of services offered to new and established
								nonprofits these can be categorized into three primary sections:
								collaborative, education, and advocacy services.
							</p>
							<p className='portfolioproject__text'>
								With all the programs and services provided by the KNC the
								organization feels they are lacking the proper feedback from its
								current and prospective members which is why they came to us.
							</p>
						</div>
						{/* <div className='portfolioproject__container container'>
							<h3 className='section__title3'>
								<UilAnalytics className='portfolioproject__icon' />
								Results of how nonprofits perceive the importance of cost of
								membership fee as a reason for not being a member:
							</h3>
							<Image src={piechart} alt='' />
							<Image src={graph} alt='' />
						</div> */}
					</section>
				</main>
			</div>
		</>
	)
}
